{% set name = "rank_filter" %}
{% set version = "0.4.14" %}
{% set checksum = "617dddeb32d1a084fa125dc371a5c0337be8d164f5fc16b6dbe48284dd5282dc" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ checksum }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - toolchain
    - boost-cpp 1.64.*
    - python
    - setuptools >=18.0
    - numpy x.x
    - numpy >=1.7
    - cython >=0.23

  run:
    - boost-cpp 1.64.*
    - python
    - numpy x.x
    - numpy >=1.7

test:
  source_files:
    - tests

  imports:
    - rank_filter

  commands:
    - python -m unittest discover -s .

about:
  home: https://github.com/nanshe-org/rank_filter
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'A simple python module containing an in-place linear rank filter optimized in C++.'

extra:
  recipe-maintainers:
    - jakirkham
