{% set name = "rank_filter" %}
{% set version = "0.5.0" %}
{% set checksum = "ff6940544d7cb98d4c8f2a78bda75f2da5e5b2e27bf0d36bcb18168a5280ddb2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ checksum }}

build:
  number: 1000
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - boost-cpp
    - python
    - pip
    - setuptools >=18.0
    - numpy
    - cython >=0.23
  run:
    - boost-cpp
    - python
    - {{ pin_compatible('numpy') }}

test:
  source_files:
    - tests

  imports:
    - rank_filter

  commands:
    - python -m unittest discover -s .

about:
  home: https://github.com/nanshe-org/rank_filter
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'A simple python module containing an in-place linear rank filter optimized in C++.'

extra:
  recipe-maintainers:
    - jakirkham
