{% set name = "rank_filter" %}
{% set version = "0.5.2" %}
{% set checksum = "1dbd3ee93168ad0a61599adf31c2959a48830d122c82e91cb3d2df2af67745ea" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ checksum }}

build:
  number: 1005
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - boost-cpp
    - python
    - pip
    - setuptools >=18.0
    - numpy
    - cython >=0.23
  run:
    - boost-cpp
    - python
    - {{ pin_compatible('numpy') }}

test:
  source_files:
    - tests

  imports:
    - rank_filter

  commands:
    - python -m unittest discover -s .

about:
  home: https://github.com/nanshe-org/rank_filter
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: 'A simple python module containing an in-place linear rank filter optimized in C++.'

extra:
  recipe-maintainers:
    - jakirkham
