appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: iWwd8DCHm0KnEYahVOr7T/TQl0ubyBwpRMm6usN9Q/oDCStW81XlqCHAfDfeXjoiy+IuDoBj1sOrZdw5cn66pfClgPuJ40xPG02XpBV08N7uL4tsjvP134CSX/QkxjEgExY2wC9htQZIh9wnpisD4qc2Kn9+Z+NiO/SfUL/h/E5KiH7H6072V5Nmd7gfAs5jjDfy+0qJOZbxnoepB6Dk1w7Q4CnAShGMtNSQ1VMLHhYUF9uSYzEccUBwugQKhQAefSy5fgyQUXvN3Wq9AzgmYNe55J/8aECL56TULh27rIA1qgaSD3aDP1vjnGS9cSHdQtnskhqvGPFu3P8Qw1+4JT6ljGRaMfLLV9C/1/HYzu3ISh/3AgJ8T7mIDqjF1z2s79IYeS5YjCrB3W67WMMgLDPo+Pf4NWF8puexsGcCx4RQUGMvGFa4EcB/Py3aen7s4/5otNQHm4Jb9v2UbNLgbvRTt6Eiufw9HSFn6tmppgN7JnhYCj4wrxc5m86nHNVr3sUizr/kULyVvDZp9jzKyms5c+wI1DZmvS/G1spX+EswqQJx4lPG+/UN7qI1qeD3S9FROPuO9Db3SwQe4r9uJDixp7+qKW+NtsY44KHYZ1/2hBo8xq4+OcdrVIiZq9LMa6QZgb2J1BuxnNa5l5iBVF5HSxORZyYYjGXNAQNXNSo=}
